name: Print README

on:
  workflow_dispatch:

jobs:
  print-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print README
        run: cat README.md
